In [1]:
from __future__ import print_function 
from __future__ import division
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
import torchvision
from torchvision import datasets, models, transforms
import matplotlib.pyplot as plt
import time
import os
import copy

In [1]:
import import_ipynb

from tools.Midline_Reformater import reformat_midline

importing Jupyter notebook from /home/cyril_b/projects/schmidtea/tools/Midline_Reformater.ipynb


In [5]:
pip freeze > requirements.txt

Note: you may need to restart the kernel to use updated packages.


In [2]:
errorlist = [((1, 2), 3), ((4, 5), 6), ((7, 8), 9), ((10, 11), 12)]


In [4]:
errorlist[0]

((1, 2), 3)

In [1]:
errorlist = [((1, 2), 3), ((4, 5), 6), ((7, 8), 9), ((10, 11), 12)]

f = open("filee.txt", "w")
f.writelines(nthstring + '\n' for nthstring in errorlist)

TypeError: can only concatenate tuple (not "str") to tuple

In [3]:
from sys import getsizeof
getsizeof(x)

28

In [5]:
for i in dir():
    print('variable: {}, size: {}'.format(i, getsizeof(i)))

variable: In, size: 51
variable: Out, size: 52
variable: _, size: 50
variable: _3, size: 51
variable: _4, size: 51
variable: __, size: 51
variable: ___, size: 52
variable: __builtin__, size: 60
variable: __builtins__, size: 61
variable: __doc__, size: 56
variable: __loader__, size: 59
variable: __name__, size: 57
variable: __package__, size: 60
variable: __spec__, size: 57
variable: _dh, size: 52
variable: _i, size: 51
variable: _i1, size: 52
variable: _i2, size: 52
variable: _i3, size: 52
variable: _i4, size: 52
variable: _i5, size: 52
variable: _ih, size: 52
variable: _ii, size: 52
variable: _iii, size: 53
variable: _oh, size: 52
variable: exit, size: 53
variable: get_ipython, size: 60
variable: getsizeof, size: 58
variable: quit, size: 53
variable: x, size: 50


In [2]:
def addatition():
    return x + 2

print(addatition())

4


In [2]:
import numpy as np

In [ ]:
data_transforms = {
        transforms.Compose([
        transforms.RandomResizedCrop(224),
        transforms.RandomHorizontalFlip(),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ])
    

In [ ]:
transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])

In [17]:
x = [[25, 30], [250, 100]]

y = np.array(x)

y_reshape = y.reshape((1,2,2))

In [18]:
y_reshape

array([[[ 25,  30],
        [250, 100]]])

In [19]:
y_tensor = torch.from_numpy(y_reshape).type(torch.float)

In [15]:
y_tensor

tensor([[[[ 25.,  30.],
          [250., 100.]]]])

In [23]:
y_tensor_normalized = transforms.Normalize([0.485], [0.225])(y_tensor)

In [25]:
y_tensor_normalized.shape

torch.Size([1, 2, 2])

In [5]:
import torch
import numpy as np

x = np.array([1,2], dtype = 'float')
x_torch = torch.from_numpy(x)
x_torch_double = x_torch.double()
x_torch_double_bis = x_torch.type(torch.DoubleTensor)


print(x.dtype)
print(x_torch.dtype)
print(x_torch_double.dtype)
print(x_torch_double_bis.dtype)

float64
torch.float64
torch.float64
torch.float64


In [51]:
import numpy as np

In [79]:
a = np.arange(10)
a.shape
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
a.flatten()
a.shape
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
np.where(a == min(abs(a-4))+4, True, False)

array([False, False, False, False,  True, False, False, False, False,
       False])

In [88]:
i = 4

hop = np.where(a == min(abs(a-i))+i)

print(hop[0][0])

4


In [74]:
hop

(array([2], dtype=int64),)

In [7]:
b, c = a

In [41]:
from tqdm import tqdm
from tqdm.notebook import trange

In [17]:
phrase = "S"

In [45]:
for idx, letter in enumerate(trange(len(phrase*2000))):
    print("idx: {}, letter:{}".format(idx, letter))
    

idx: 0, letter:0
idx: 1, letter:1
idx: 2, letter:2
idx: 3, letter:3
idx: 4, letter:4
idx: 5, letter:5
idx: 6, letter:6
idx: 7, letter:7
idx: 8, letter:8
idx: 9, letter:9
idx: 10, letter:10
idx: 11, letter:11
idx: 12, letter:12
idx: 13, letter:13
idx: 14, letter:14
idx: 15, letter:15
idx: 16, letter:16
idx: 17, letter:17
idx: 18, letter:18
idx: 19, letter:19
idx: 20, letter:20
idx: 21, letter:21
idx: 22, letter:22
idx: 23, letter:23
idx: 24, letter:24
idx: 25, letter:25
idx: 26, letter:26
idx: 27, letter:27
idx: 28, letter:28
idx: 29, letter:29
idx: 30, letter:30
idx: 31, letter:31
idx: 32, letter:32
idx: 33, letter:33
idx: 34, letter:34
idx: 35, letter:35
idx: 36, letter:36
idx: 37, letter:37
idx: 38, letter:38
idx: 39, letter:39
idx: 40, letter:40
idx: 41, letter:41
idx: 42, letter:42
idx: 43, letter:43
idx: 44, letter:44
idx: 45, letter:45
idx: 46, letter:46
idx: 47, letter:47
idx: 48, letter:48
idx: 49, letter:49
idx: 50, letter:50
idx: 51, letter:51
idx: 52, letter:52
idx: 53, lett